Repository react-navigation/react-navigation, pull requests merged in 2018-06, with the labels that each got.

#4317 [flow] Fix NavigationScreenComponent's navigationOptions
  flow/react-navigation.js
Labels: flow

#4353 Make headers of non-standard heights work correctly in StackNavigator when header is null (Fixes #4208)
  examples/NavigationPlayground/js/App.js
  examples/NavigationPlayground/js/StacksOverTopTabs.js
  examples/NavigationPlayground/package.json
  examples/NavigationPlayground/yarn.lock
  src/navigators/__tests__/__snapshots__/NestedNavigator-test.js.snap
  src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap
  src/views/StackView/StackViewLayout.js
Labels: needs action from maintainer

#4188 Add <NavigationEvents/> component
  examples/NavigationPlayground/js/App.js
  examples/NavigationPlayground/js/TabsWithNavigationEvents.js
  flow/react-navigation.js
  src/react-navigation.js
  src/react-navigation.web.js
  src/views/NavigationEvents.js
  src/views/__tests__/NavigationEvents-test.js
Labels: discussion required
