Repository react-navigation/react-navigation, pull requests merged in 2018-02, with the labels that each got.

#3304 Pass prevTransitionsProps to transitionConfig
  src/views/CardStack/CardStack.js
  src/views/CardStack/CardStackTransitioner.js
Labels: PR: needs review

#2498 getComponentForState made more generic
  src/routers/TabRouter.js
Labels: needs more info

#3593 Fix bug #3279 “Action within RESET doesn't trigger”
  src/routers/StackRouter.js
Labels: PR: revision needed
